"""Probe OCI Enterprise AI Vision through the OpenAI Responses SDK.

Required environment variables:
  OCI_ENTERPRISE_AI_ENDPOINT
  OCI_ENTERPRISE_AI_PROJECT_OCID
  OCI_ENTERPRISE_AI_API_KEY

Optional:
  OCI_ENTERPRISE_AI_MODEL
"""

from __future__ import annotations

import base64
import os
import sys

from openai import OpenAI

TEST_IMAGE_JPEG_BASE64 = (
    "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsO"
    "CwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ"
    "EBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAIAAgADASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAA"
    "AAYJA//EACQQAQABAAsBAQEBAAAAAAAAAAAHAwQFBhc3V3aWtNMBAhEh/8QAGQEBAAMBAQAAAAAAAAAAAAAAAAMH"
    "CAQB/8QAKBEBAAECAA8BAQAAAAAAAAAAAAECAwQFExUzNFJTcXKRkrGy0TER/9oADAMBAAIRAxEAPwDVMAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGJgCrG8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGvkHZKR"
    "/tayupRLdEQdkpH+1rK6lEt1nWNFTwjww3jXX7/PV7SAJXAAAAAAAAAAAAAAAAAAAAAxMAVY3mAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAA18g7JSP9rWV1KJboiDslI/2tZXUolus6xoqeEeGG8a6/f56vaQBK4AAAAAAAAAAA"
    "AAAAAAAAAGJgCrG8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGvkHZKR/tayupRLdEQdkpH+1rK6lEt1nWN"
    "FTwjww3jXX7/AD1e0gCVwAAAAAAAAAAAAAAAAAAAAMTAFWN5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANf"
    "IOyUj/a1ldSiW6Ig7JSP9rWV1KJbrOsaKnhHhhvGuv3+er2kASuAAAAAAAAAAAAAAAAAAAABiYAqxvMAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAABr5B2Skf7WsrqUS3REHZKR/tayupRLdZ1jRU8I8MN411+/z1e0gCVwAAAAAA"
    "AAAAAAAAAAAAAAMTAFWN5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANfIOyUj/a1ldSiW6Ig7JSP9rWV1KJ"
    "brOsaKnhHhhvGuv3+er2kASuAAAAAAAAAAAAAAAAAAAABiYAqxvMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "ABr5B2Skf7WsrqUS3REHZKR/tayupRLdZ1jRU8I8MN411+/z1e0gCVwAAAAAAAAAAAAAAAAAAAAMTAFWN5gAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANfIOyUj/AGtZXUoluiIOyUj/AGtZXUolus6xoqeEeGG8a6/f56vaQBK4"
    "AAAAAAAAAAAAAAAAAAAAGJgCrG8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGvkHZKR/tayupRLdEQdkpH+"
    "1rK6lEt1nWNFTwjww3jXX7/PV7SAJXAAAAAAAAAAAAAAAAAAAAAxMAVY3mAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAA18g7JSP9rWV1KJboiDslI/2tZXUolus6xoqeEeGG8a6/f56vaQBK4AAAAAAAAAAAAAAAAAAAAGJgCrG8"
    "wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGvkHZKR/tayupRLdEQdkpH+1rK6lEt1nWNFTwjww3jXX7/AD1e"
    "0gCVwAAAAAAAAAAAAAAAAAAAAMTAFWN5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANfIOyUj/a1ldSiW6Ig"
    "7JSP9rWV1KJbrOsaKnhHhhvGuv3+er2kASuAAAAAAAAAAAAAAAAAAAABiYAqxvMAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAABr5B2Skf7WsrqUS3REHZKR/tayupRLdZ1jRU8I8MN411+/z1e0gCVwAAAAAAAAAAAAAAAAAAAAMT"
    "AFWN5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANfIOyUj/a1ldSiW6Ig7JSP9rWV1KJbrOsaKnhHhhvGuv3"
    "+er2kASuAAAAAAAAAAAAAAAAAAAABiYAqxvMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABr5B2Skf7WsrqUS"
    "3REHZKR/tayupRLdZ1jRU8I8MN411+/z1e0gCVwAAAAAAAAAAAAAAAAAAAAMTAFWN5gAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAANfIOyUj/AGtZXUoluiIOyUj/AGtZXUolus6xoqeEeGG8a6/f56vaQBK4AAAAAAAAAAAAAAAA"
    "AAAAGJgCrG8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGvkHZKR/tayupRLdEQdkpH+1rK6lEt1nWNFTwjw"
    "w3jXX7/PV7SAJXAAAAAAAAAAAAAAAAAAAAAxMAVY3mAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA18g7JSP9"
    "rWV1KJboiDslI/2tZXUolus6xoqeEeGG8a6/f56vaQBK4AAAAAAAAAAAAAAAAAAAAGJgCrG8wAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAGvkHZKR/tayupRLdEQdkpH+1rK6lEt1nWNFTwjww3jXX7/AD1e0gCVwAAAAAAAAAAA"
    "AAAAAAAAAMTAFWN5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANfIOyUj/a1ldSiW6Ig7JSP9rWV1KJbrOsa"
    "KnhHhhvGuv3+er2kASuAAAAAAAAAAAAAAAAAAAABEYHQpo/cnj9U8zA6FNH7k8fqnmtxFkLWzHSHfnXD9/X3VfUR"
    "gdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkGdcP39fdV9RGB0KaP3J4/VPMwOhTR+5PH6p5rcMha2Y6QZ1w/f191X1"
    "EYHQpo/cnj9U8zA6FNH7k8fqnmtwyFrZjpBnXD9/X3VfURgdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkGdcP39fdV"
    "9RGB0KaP3J4/VPMwOhTR+5PH6p5rcMha2Y6QZ1w/f191X1EYHQpo/cnj9U8zA6FNH7k8fqnmtwyFrZjpBnXD9/X3"
    "VfURgdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkGdcP39fdV9RGB0KaP3J4/VPMwOhTR+5PH6p5rcMha2Y6QZ1w/f1"
    "91X1EYHQpo/cnj9U8zA6FNH7k8fqnmtwyFrZjpBnXD9/X3VfURgdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkGdcP3"
    "9fdV9RGB0KaP3J4/VPMwOhTR+5PH6p5rcMha2Y6QZ1w/f191X1EYHQpo/cnj9U8zA6FNH7k8fqnmtwyFrZjpBnXD"
    "9/X3VfURgdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkGdcP39fdV9RGB0KaP3J4/VPMwOhTR+5PH6p5rcMha2Y6QZ1"
    "w/f191X1EYHQpo/cnj9U8zA6FNH7k8fqnmtwyFrZjpBnXD9/X3VfURgdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkG"
    "dcP39fdV9RGB0KaP3J4/VPMwOhTR+5PH6p5rcMha2Y6QZ1w/f191X1EYHQpo/cnj9U8zA6FNH7k8fqnmtwyFrZjp"
    "BnXD9/X3VfURgdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkGdcP39fdV9cKjUalZdSq9m2bU6CqVOqUX4oKvV6Cj+U"
    "dHQ0f5+fPz+fx+Pz+f58/P5+fPnz58+fP8+fPjuCX8cMzNU/2f0AHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//2Q=="
)


def main() -> int:
    endpoint = _required_env("OCI_ENTERPRISE_AI_ENDPOINT")
    project_ocid = _required_env("OCI_ENTERPRISE_AI_PROJECT_OCID")
    api_key = _required_env("OCI_ENTERPRISE_AI_API_KEY")
    model = os.getenv("OCI_ENTERPRISE_AI_MODEL", "google.gemini-2.5-flash").strip()

    _validate_test_image()
    client = OpenAI(
        base_url=endpoint,
        api_key=api_key,
        project=project_ocid,
        timeout=60.0,
        max_retries=2,
    )
    response = client.responses.create(
        model=model,
        input=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": (
                            "The image contains one large colored square on a white background. "
                            "Return only the square color in English."
                        ),
                    },
                    {
                        "type": "input_image",
                        "image_url": f"data:image/jpeg;base64,{TEST_IMAGE_JPEG_BASE64}",
                    },
                ],
            }
        ],
    )

    output_text = str(getattr(response, "output_text", "")).strip()
    print(f"model={model}")
    print(f"output_text={output_text}")
    normalized = output_text.strip().lower()
    color_words = ("red", "scarlet", "crimson")
    if not any(word in normalized for word in color_words):
        print("ERROR: response did not identify the red square.", file=sys.stderr)
        return 2
    print("OK: OpenAI Responses Vision probe succeeded.")
    return 0


def _required_env(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        print(f"ERROR: {name} is required.", file=sys.stderr)
        raise SystemExit(2)
    return value


def _validate_test_image() -> None:
    data = base64.b64decode(TEST_IMAGE_JPEG_BASE64)
    if not data.startswith(b"\xff\xd8"):
        raise RuntimeError("test image is not a JPEG")
    if len(data) < 1024:
        raise RuntimeError("test image is too small for a reliable vision probe")


if __name__ == "__main__":
    raise SystemExit(main())
