-- NL2SQL system schema migration ledger and cross-replica operation lease.
-- This control migration is applied only by an explicit API / CLI operation.

CREATE TABLE NL2SQL_SCHEMA_MIGRATIONS (
    VERSION_NO NUMBER(10) PRIMARY KEY,
    DESCRIPTION VARCHAR2(256) NOT NULL,
    CHECKSUM VARCHAR2(64) NOT NULL,
    APPLIED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE NL2SQL_SCHEMA_OPERATIONS (
    OPERATION_KEY VARCHAR2(32) PRIMARY KEY,
    STATUS VARCHAR2(16) DEFAULT 'IDLE' NOT NULL,
    OPERATION_KIND VARCHAR2(16),
    LEASE_OWNER VARCHAR2(64),
    LEASE_EXPIRES_AT TIMESTAMP WITH TIME ZONE,
    LAST_ERROR_CODE VARCHAR2(64),
    SCHEMA_EPOCH NUMBER(19) DEFAULT 0 NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_NL2SQL_SCHEMA_OP_STATUS
        CHECK (STATUS IN ('IDLE', 'RUNNING', 'FAILED'))
);

INSERT INTO NL2SQL_SCHEMA_OPERATIONS
    (OPERATION_KEY, STATUS, SCHEMA_EPOCH)
VALUES ('system_schema', 'IDLE', 0);
