-- Base versioned Ontology storage. Runtime code only checks these objects and never creates them.

CREATE TABLE NL2SQL_ONTOLOGY_REVISIONS (
    REVISION_ID VARCHAR2(128) PRIMARY KEY,
    STATUS VARCHAR2(32) NOT NULL,
    SCHEMA_FINGERPRINT VARCHAR2(64) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE NL2SQL_ONTOLOGY_NODES (
    REVISION_ID VARCHAR2(128) NOT NULL,
    NODE_ID VARCHAR2(128) NOT NULL,
    NODE_TYPE VARCHAR2(48) NOT NULL,
    REVIEW_STATUS VARCHAR2(32) NOT NULL,
    PHYSICAL_ID VARCHAR2(128),
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    EMBEDDING VECTOR(1536, FLOAT32),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_ONT_NODES PRIMARY KEY (REVISION_ID, NODE_ID)
);

CREATE TABLE NL2SQL_ONTOLOGY_EDGES (
    REVISION_ID VARCHAR2(128) NOT NULL,
    EDGE_ID VARCHAR2(128) NOT NULL,
    SOURCE_NODE_ID VARCHAR2(128) NOT NULL,
    TARGET_NODE_ID VARCHAR2(128) NOT NULL,
    REVIEW_STATUS VARCHAR2(32) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_ONT_EDGES PRIMARY KEY (REVISION_ID, EDGE_ID)
);

CREATE TABLE NL2SQL_ONTOLOGY_PROFILE_VIEWS (
    PROFILE_ID VARCHAR2(128) PRIMARY KEY,
    REVISION_ID VARCHAR2(128) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE NL2SQL_ONTOLOGY_QUERY_SESSIONS (
    SESSION_ID VARCHAR2(128) PRIMARY KEY,
    ONTOLOGY_REVISION_ID VARCHAR2(128) NOT NULL,
    PROFILE_ID VARCHAR2(128) NOT NULL,
    STATUS VARCHAR2(48) NOT NULL,
    INTENT_VERSION NUMBER(19) DEFAULT 0 NOT NULL,
    SQL_VERSION NUMBER(19) DEFAULT 0 NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE NL2SQL_ONTOLOGY_ARTIFACTS (
    ARTIFACT_ID VARCHAR2(128) PRIMARY KEY,
    SESSION_ID VARCHAR2(128) NOT NULL,
    ARTIFACT_TYPE VARCHAR2(48) NOT NULL,
    CONTENT_HASH VARCHAR2(64) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE NL2SQL_ONTOLOGY_PROPOSALS (
    PROPOSAL_ID VARCHAR2(128) PRIMARY KEY,
    SESSION_ID VARCHAR2(128) NOT NULL,
    ONTOLOGY_REVISION_ID VARCHAR2(128) NOT NULL,
    PROFILE_ID VARCHAR2(128) NOT NULL,
    STATUS VARCHAR2(32) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE NL2SQL_ONTOLOGY_IDEMPOTENCY (
    OPERATION VARCHAR2(96) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(160) NOT NULL,
    REQUEST_HASH VARCHAR2(64) NOT NULL,
    RESOURCE_ID VARCHAR2(160) NOT NULL,
    STATUS VARCHAR2(32) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_ONT_IDEMPOTENCY PRIMARY KEY (OPERATION, IDEMPOTENCY_KEY)
);

CREATE INDEX IX_NL2SQL_ONT_NODE_PHYSICAL
    ON NL2SQL_ONTOLOGY_NODES (PHYSICAL_ID);
CREATE VECTOR INDEX IX_NL2SQL_ONT_NODE_EMBED
    ON NL2SQL_ONTOLOGY_NODES (EMBEDDING)
    ORGANIZATION INMEMORY NEIGHBOR GRAPH DISTANCE COSINE;
CREATE INDEX IX_NL2SQL_ONT_EDGE_SOURCE
    ON NL2SQL_ONTOLOGY_EDGES (REVISION_ID, SOURCE_NODE_ID);
CREATE INDEX IX_NL2SQL_ONT_EDGE_TARGET
    ON NL2SQL_ONTOLOGY_EDGES (REVISION_ID, TARGET_NODE_ID);
CREATE INDEX IX_NL2SQL_ONT_SESSION_PROFILE
    ON NL2SQL_ONTOLOGY_QUERY_SESSIONS (PROFILE_ID, UPDATED_AT);
CREATE INDEX IX_NL2SQL_ONT_ART_SESSION
    ON NL2SQL_ONTOLOGY_ARTIFACTS (SESSION_ID, ARTIFACT_TYPE);
CREATE INDEX IX_NL2SQL_ONT_PROP_SESSION
    ON NL2SQL_ONTOLOGY_PROPOSALS (SESSION_ID, STATUS);
CREATE INDEX IX_NL2SQL_ONT_IDEMPOTENCY_RESOURCE
    ON NL2SQL_ONTOLOGY_IDEMPOTENCY (RESOURCE_ID, STATUS);
