-- Ontology source/job persistence and Oracle RDF staging.
-- Production operators apply this migration explicitly; application startup does not run it.

CREATE TABLE NL2SQL_ONTOLOGY_SOURCE_DOCS (
    SOURCE_DOCUMENT_ID VARCHAR2(128) PRIMARY KEY,
    PROFILE_ID VARCHAR2(128) NOT NULL,
    STATUS VARCHAR2(32) NOT NULL,
    SHA256 VARCHAR2(64) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE NL2SQL_ONTOLOGY_JOBS (
    JOB_ID VARCHAR2(128) PRIMARY KEY,
    JOB_TYPE VARCHAR2(32) NOT NULL,
    PROFILE_ID VARCHAR2(128) NOT NULL,
    STATUS VARCHAR2(32) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE NL2SQL_ONTOLOGY_RECOMMENDATIONS (
    RECOMMENDATION_ID VARCHAR2(128) PRIMARY KEY,
    QUESTION_HASH VARCHAR2(64) NOT NULL,
    STATUS VARCHAR2(32) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE SEQUENCE NL2SQL_ONTOLOGY_RDF_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE NL2SQL_ONTOLOGY_RDF_DATA (
    ID NUMBER PRIMARY KEY,
    TRIPLE SDO_RDF_TRIPLE_S
);

CREATE INDEX IX_NL2SQL_ONT_SOURCE_PROFILE
    ON NL2SQL_ONTOLOGY_SOURCE_DOCS (PROFILE_ID, STATUS);
CREATE INDEX IX_NL2SQL_ONT_JOB_STATE
    ON NL2SQL_ONTOLOGY_JOBS (JOB_TYPE, STATUS, UPDATED_AT);
CREATE INDEX IX_NL2SQL_ONT_REC_QUESTION
    ON NL2SQL_ONTOLOGY_RECOMMENDATIONS (QUESTION_HASH, STATUS);

-- Exactly one active published revision. A publish transaction archives the old row first.
CREATE UNIQUE INDEX UX_NL2SQL_ONT_ONE_PUBLISHED
    ON NL2SQL_ONTOLOGY_REVISIONS (CASE WHEN STATUS = 'published' THEN 1 END);
