-- Incremental NL2SQL state, schema catalog, and migration outbox.
-- Apply through `python -m app.cli.nl2sql_migrate_state --apply-ddl`.
-- The CLI tolerates ORA-00955 so this artifact is safe to re-apply.

CREATE TABLE NL2SQL_SCHEMA_MIGRATIONS (
    VERSION_NO NUMBER(10) PRIMARY KEY,
    DESCRIPTION VARCHAR2(256) NOT NULL,
    CHECKSUM VARCHAR2(64) NOT NULL,
    APPLIED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE NL2SQL_CHANGE_TOKENS (
    NAMESPACE VARCHAR2(64) PRIMARY KEY,
    CHANGE_SEQ NUMBER(19) DEFAULT 0 NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE NL2SQL_PROFILES (
    PROFILE_ID VARCHAR2(128) PRIMARY KEY,
    NAME VARCHAR2(512) NOT NULL,
    CATEGORY VARCHAR2(256),
    DESCRIPTION VARCHAR2(2000),
    ARCHIVED NUMBER(1) DEFAULT 0 NOT NULL,
    ALLOWED_TABLE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    ALLOWED_VIEW_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    GLOSSARY_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    FEW_SHOT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IX_NL2SQL_PROFILES_LIST
    ON NL2SQL_PROFILES (ARCHIVED, UPPER(NAME), PROFILE_ID);

ALTER TABLE NL2SQL_PROFILES
    MODIFY (CATEGORY NULL, DESCRIPTION NULL);

CREATE TABLE NL2SQL_SCHEMA_CATALOG_HEAD (
    HEAD_KEY VARCHAR2(32) PRIMARY KEY,
    CATALOG_VERSION NUMBER(19) NOT NULL,
    SCHEMA_FINGERPRINT VARCHAR2(64),
    REFRESHED_AT VARCHAR2(64),
    OBJECT_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
    COLUMN_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE NL2SQL_SCHEMA_CATALOG_HEAD
    MODIFY (SCHEMA_FINGERPRINT NULL, REFRESHED_AT NULL);

CREATE TABLE NL2SQL_SCHEMA_OBJECTS (
    OWNER_NAME VARCHAR2(128) NOT NULL,
    OBJECT_NAME VARCHAR2(128) NOT NULL,
    OBJECT_TYPE VARCHAR2(32) NOT NULL,
    LOGICAL_NAME VARCHAR2(512),
    COMMENTS VARCHAR2(2000),
    ROW_COUNT NUMBER(19),
    COLUMN_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    LAST_DDL_AT VARCHAR2(64),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_SCHEMA_OBJECTS PRIMARY KEY (OWNER_NAME, OBJECT_NAME)
);

CREATE INDEX IX_NL2SQL_SCHEMA_OBJECT_LIST
    ON NL2SQL_SCHEMA_OBJECTS (OBJECT_TYPE, OWNER_NAME, OBJECT_NAME);

ALTER TABLE NL2SQL_SCHEMA_OBJECTS
    MODIFY (LOGICAL_NAME NULL, COMMENTS NULL, LAST_DDL_AT NULL);

CREATE TABLE NL2SQL_SCHEMA_COLUMNS (
    OWNER_NAME VARCHAR2(128) NOT NULL,
    OBJECT_NAME VARCHAR2(128) NOT NULL,
    COLUMN_NAME VARCHAR2(128) NOT NULL,
    COLUMN_POSITION NUMBER(10) NOT NULL,
    LOGICAL_NAME VARCHAR2(512),
    DATA_TYPE VARCHAR2(256) NOT NULL,
    NULLABLE NUMBER(1) DEFAULT 1 NOT NULL,
    COMMENTS VARCHAR2(2000),
    SAMPLE_VALUES_JSON CLOB CHECK (SAMPLE_VALUES_JSON IS JSON),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_SCHEMA_COLUMNS
        PRIMARY KEY (OWNER_NAME, OBJECT_NAME, COLUMN_NAME),
    CONSTRAINT FK_NL2SQL_SCHEMA_COLUMNS_OBJECT
        FOREIGN KEY (OWNER_NAME, OBJECT_NAME)
        REFERENCES NL2SQL_SCHEMA_OBJECTS (OWNER_NAME, OBJECT_NAME) ON DELETE CASCADE
);

CREATE INDEX IX_NL2SQL_SCHEMA_COLUMN_SEARCH
    ON NL2SQL_SCHEMA_COLUMNS (OWNER_NAME, OBJECT_NAME, COLUMN_POSITION);

ALTER TABLE NL2SQL_SCHEMA_COLUMNS
    MODIFY (LOGICAL_NAME NULL, COMMENTS NULL);

CREATE TABLE NL2SQL_SCHEMA_CONSTRAINTS (
    OWNER_NAME VARCHAR2(128) NOT NULL,
    OBJECT_NAME VARCHAR2(128) NOT NULL,
    CONSTRAINT_NAME VARCHAR2(128) NOT NULL,
    CONSTRAINT_TEXT VARCHAR2(2000),
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_SCHEMA_CONSTRAINTS
        PRIMARY KEY (OWNER_NAME, OBJECT_NAME, CONSTRAINT_NAME),
    CONSTRAINT FK_NL2SQL_SCHEMA_CONSTRAINT_OBJECT
        FOREIGN KEY (OWNER_NAME, OBJECT_NAME)
        REFERENCES NL2SQL_SCHEMA_OBJECTS (OWNER_NAME, OBJECT_NAME) ON DELETE CASCADE
);

ALTER TABLE NL2SQL_SCHEMA_CONSTRAINTS
    MODIFY (CONSTRAINT_TEXT NULL);

CREATE TABLE NL2SQL_SCHEMA_DEPENDENCIES (
    OWNER_NAME VARCHAR2(128) NOT NULL,
    VIEW_NAME VARCHAR2(128) NOT NULL,
    REFERENCED_OWNER VARCHAR2(128) NOT NULL,
    REFERENCED_NAME VARCHAR2(128) NOT NULL,
    REFERENCED_TYPE VARCHAR2(32) NOT NULL,
    CONSTRAINT PK_NL2SQL_SCHEMA_DEPENDENCIES PRIMARY KEY (
        OWNER_NAME, VIEW_NAME, REFERENCED_OWNER, REFERENCED_NAME
    )
);

CREATE TABLE NL2SQL_SCHEMA_SAMPLES (
    OWNER_NAME VARCHAR2(128) NOT NULL,
    OBJECT_NAME VARCHAR2(128) NOT NULL,
    COLUMN_NAME VARCHAR2(128) NOT NULL,
    VALUES_JSON CLOB CHECK (VALUES_JSON IS JSON) NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_SCHEMA_SAMPLES
        PRIMARY KEY (OWNER_NAME, OBJECT_NAME, COLUMN_NAME)
);

CREATE TABLE NL2SQL_SCHEMA_REFRESH_JOBS (
    JOB_ID VARCHAR2(128) PRIMARY KEY,
    STATUS VARCHAR2(32) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IX_NL2SQL_SCHEMA_REFRESH_STATE
    ON NL2SQL_SCHEMA_REFRESH_JOBS (STATUS, UPDATED_AT);

CREATE TABLE NL2SQL_STATE_DOCUMENTS (
    COLLECTION VARCHAR2(64) NOT NULL,
    ENTITY_ID VARCHAR2(128) NOT NULL,
    PROFILE_ID VARCHAR2(128),
    STATUS VARCHAR2(32),
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_STATE_DOCUMENTS PRIMARY KEY (COLLECTION, ENTITY_ID)
);

CREATE INDEX IX_NL2SQL_STATE_DOCUMENT_LIST
    ON NL2SQL_STATE_DOCUMENTS (COLLECTION, PROFILE_ID, STATUS, UPDATED_AT);

ALTER TABLE NL2SQL_STATE_DOCUMENTS
    MODIFY (PROFILE_ID NULL, STATUS NULL);

CREATE TABLE NL2SQL_MIGRATION_OUTBOX (
    OUTBOX_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SNAPSHOT_VERSION NUMBER(19) NOT NULL,
    SNAPSHOT_CHECKSUM VARCHAR2(64) NOT NULL,
    STATE_JSON CLOB CHECK (STATE_JSON IS JSON) NOT NULL,
    PROCESSED_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE SEQUENCE NL2SQL_MIGRATION_SNAPSHOT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE UNIQUE INDEX UX_NL2SQL_MIGRATION_OUTBOX_VERSION
    ON NL2SQL_MIGRATION_OUTBOX (SNAPSHOT_VERSION);

CREATE TABLE NL2SQL_ONTOLOGY_PROFILE_VIEW_REVISIONS (
    PROFILE_ID VARCHAR2(128) NOT NULL,
    REVISION_ID VARCHAR2(128) NOT NULL,
    VERSION_NO NUMBER(19) NOT NULL,
    ETAG VARCHAR2(64) NOT NULL,
    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_ONT_PROFILE_VIEW_REV PRIMARY KEY (PROFILE_ID, REVISION_ID)
);

CREATE INDEX IX_NL2SQL_ONT_VIEW_REVISION
    ON NL2SQL_ONTOLOGY_PROFILE_VIEW_REVISIONS (REVISION_ID, PROFILE_ID);

INSERT INTO NL2SQL_ONTOLOGY_PROFILE_VIEW_REVISIONS
    (PROFILE_ID, REVISION_ID, VERSION_NO, ETAG, PAYLOAD_JSON, CREATED_AT, UPDATED_AT)
SELECT PROFILE_ID, REVISION_ID, VERSION_NO, ETAG, PAYLOAD_JSON, CREATED_AT, UPDATED_AT
FROM NL2SQL_ONTOLOGY_PROFILE_VIEWS;

INSERT INTO NL2SQL_CHANGE_TOKENS (NAMESPACE, CHANGE_SEQ) VALUES ('profiles', 0);
INSERT INTO NL2SQL_CHANGE_TOKENS (NAMESPACE, CHANGE_SEQ) VALUES ('schema', 0);
INSERT INTO NL2SQL_CHANGE_TOKENS (NAMESPACE, CHANGE_SEQ) VALUES ('state', 0);

-- Oracle treats an empty string as NULL, so a mandatory empty-string default on a
-- populated legacy table fails with ORA-01758.  Add the column nullable,
-- recover the profile from the proposal/session payload, then enforce the
-- invariant after every legacy row has a deterministic value.
ALTER TABLE NL2SQL_ONTOLOGY_PROPOSALS
    ADD (PROFILE_ID VARCHAR2(128));

UPDATE NL2SQL_ONTOLOGY_PROPOSALS proposal
SET PROFILE_ID = COALESCE(
    JSON_VALUE(
        proposal.PAYLOAD_JSON,
        '$.profile_id' RETURNING VARCHAR2(128) NULL ON ERROR
    ),
    (
        SELECT MAX(session_row.PROFILE_ID)
        FROM NL2SQL_ONTOLOGY_QUERY_SESSIONS session_row
        WHERE session_row.SESSION_ID = proposal.SESSION_ID
    ),
    '__legacy__'
)
WHERE PROFILE_ID IS NULL;

ALTER TABLE NL2SQL_ONTOLOGY_PROPOSALS
    MODIFY (PROFILE_ID NOT NULL);

CREATE INDEX IX_NL2SQL_ONT_PROPOSAL_PROFILE
    ON NL2SQL_ONTOLOGY_PROPOSALS (PROFILE_ID, STATUS, UPDATED_AT);

INSERT INTO NL2SQL_SCHEMA_MIGRATIONS (VERSION_NO, DESCRIPTION, CHECKSUM)
VALUES (3, 'incremental nl2sql state', 'runtime-verified');
