-- Application-local authentication, RBAC, sessions, and DeepSec ledger.
-- Apply explicitly before APP_AUTH_ENABLED=true startup.

CREATE TABLE NL2SQL_APP_USERS (
    USER_UUID VARCHAR2(36) PRIMARY KEY,
    LOGIN_USER_ID VARCHAR2(64) NOT NULL,
    LOGIN_USER_ID_NORMALIZED VARCHAR2(64) NOT NULL,
    DISPLAY_NAME VARCHAR2(256) NOT NULL,
    PASSWORD_HASH VARCHAR2(512) NOT NULL,
    STATUS VARCHAR2(16) DEFAULT 'ACTIVE' NOT NULL,
    FORCE_PASSWORD_CHANGE NUMBER(1) DEFAULT 1 NOT NULL,
    FAILED_LOGIN_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    LOCKED_UNTIL TIMESTAMP WITH TIME ZONE,
    VERSION_NO NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_NL2SQL_APP_USERS_STATUS CHECK (STATUS IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT CK_NL2SQL_APP_USERS_FORCE_PWD CHECK (FORCE_PASSWORD_CHANGE IN (0, 1))
);

CREATE UNIQUE INDEX UX_NL2SQL_APP_USERS_LOGIN_USER_ID
    ON NL2SQL_APP_USERS (LOGIN_USER_ID_NORMALIZED);

CREATE TABLE NL2SQL_APP_ROLES (
    ROLE_ID VARCHAR2(36) PRIMARY KEY,
    ROLE_CODE VARCHAR2(64) NOT NULL,
    DISPLAY_NAME VARCHAR2(256) NOT NULL,
    DESCRIPTION VARCHAR2(1000) DEFAULT '-' NOT NULL,
    IS_BUILT_IN NUMBER(1) DEFAULT 0 NOT NULL,
    ARCHIVED NUMBER(1) DEFAULT 0 NOT NULL,
    VERSION_NO NUMBER(19) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_NL2SQL_APP_ROLES_FLAGS CHECK (
        IS_BUILT_IN IN (0, 1) AND ARCHIVED IN (0, 1)
    )
);

CREATE UNIQUE INDEX UX_NL2SQL_APP_ROLES_CODE ON NL2SQL_APP_ROLES (ROLE_CODE);

CREATE TABLE NL2SQL_APP_USER_ROLES (
    USER_UUID VARCHAR2(36) NOT NULL,
    ROLE_ID VARCHAR2(36) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_APP_USER_ROLES PRIMARY KEY (USER_UUID, ROLE_ID),
    CONSTRAINT FK_NL2SQL_APP_UR_USER_UUID FOREIGN KEY (USER_UUID) REFERENCES NL2SQL_APP_USERS (USER_UUID),
    CONSTRAINT FK_NL2SQL_APP_UR_ROLE FOREIGN KEY (ROLE_ID) REFERENCES NL2SQL_APP_ROLES (ROLE_ID)
);

CREATE TABLE NL2SQL_APP_ROLE_PERMISSIONS (
    ROLE_ID VARCHAR2(36) NOT NULL,
    PERMISSION_CODE VARCHAR2(128) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_APP_ROLE_PERMISSIONS PRIMARY KEY (ROLE_ID, PERMISSION_CODE),
    CONSTRAINT FK_NL2SQL_APP_RP_ROLE FOREIGN KEY (ROLE_ID) REFERENCES NL2SQL_APP_ROLES (ROLE_ID)
);

CREATE TABLE NL2SQL_APP_DATA_ENTITLEMENTS (
    ENTITLEMENT_ID VARCHAR2(36) PRIMARY KEY,
    ROLE_ID VARCHAR2(36) NOT NULL,
    RESOURCE_CODE VARCHAR2(261) NOT NULL,
    SCOPE_CODE VARCHAR2(256) NOT NULL,
    CAPABILITY VARCHAR2(64) NOT NULL,
    TARGET_OWNER VARCHAR2(128),
    TARGET_OBJECT VARCHAR2(128),
    TARGET_TYPE VARCHAR2(32) DEFAULT 'TABLE' NOT NULL,
    COLUMN_NAMES VARCHAR2(4000) DEFAULT '[]' NOT NULL,
    SCOPE_MODE VARCHAR2(32) DEFAULT 'ALL' NOT NULL,
    SCOPE_COLUMN VARCHAR2(128),
    SCOPE_FILTERS VARCHAR2(4000) DEFAULT '[]' NOT NULL,
    DATA_GRANT_NAME VARCHAR2(128),
    SQL_CHECKSUM VARCHAR2(64),
    APPLY_STATUS VARCHAR2(16) DEFAULT 'PENDING' NOT NULL,
    APPLY_ERROR_MESSAGE VARCHAR2(2000) DEFAULT '-' NOT NULL,
    APPLIED_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_NL2SQL_APP_DE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES NL2SQL_APP_ROLES (ROLE_ID),
    CONSTRAINT CK_NL2SQL_APP_DE_TARGET_TYPE CHECK (
        TARGET_TYPE IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW')
    ),
    CONSTRAINT CK_NL2SQL_APP_DE_SCOPE_MODE CHECK (SCOPE_MODE IN ('ALL', 'COLUMN_EQUALS', 'FILTERS')),
    CONSTRAINT CK_NL2SQL_APP_DE_APPLY_STATUS CHECK (
        APPLY_STATUS IN ('PENDING', 'RUNNING', 'APPLIED', 'FAILED')
    ),
    CONSTRAINT UX_NL2SQL_APP_DE UNIQUE (ROLE_ID, RESOURCE_CODE, SCOPE_CODE, CAPABILITY)
);

CREATE TABLE NL2SQL_AUTH_SESSIONS (
    SESSION_ID VARCHAR2(36) PRIMARY KEY,
    USER_UUID VARCHAR2(36) NOT NULL,
    TOKEN_HASH VARCHAR2(64) NOT NULL,
    CSRF_TOKEN_HASH VARCHAR2(64) NOT NULL,
    IDLE_EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    ABSOLUTE_EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    LAST_SEEN_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    REVOKED_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_NL2SQL_AUTH_SESSION_USER_UUID FOREIGN KEY (USER_UUID) REFERENCES NL2SQL_APP_USERS (USER_UUID)
);

CREATE UNIQUE INDEX UX_NL2SQL_AUTH_SESSION_TOKEN ON NL2SQL_AUTH_SESSIONS (TOKEN_HASH);
CREATE INDEX IX_NL2SQL_AUTH_SESSION_USER_UUID ON NL2SQL_AUTH_SESSIONS (USER_UUID, REVOKED_AT);

CREATE TABLE NL2SQL_DEEPSEC_MIGRATIONS (
    PLAN_VERSION VARCHAR2(32) NOT NULL,
    STEP_NO NUMBER(10) NOT NULL,
    STEP_KEY VARCHAR2(128) NOT NULL,
    CHECKSUM VARCHAR2(64) NOT NULL,
    STATUS VARCHAR2(16) NOT NULL,
    ERROR_MESSAGE VARCHAR2(2000) DEFAULT '-' NOT NULL,
    EXECUTED_BY_USER_UUID VARCHAR2(36),
    EXECUTED_AT TIMESTAMP WITH TIME ZONE,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_DEEPSEC_MIGRATIONS PRIMARY KEY (PLAN_VERSION, STEP_NO),
    CONSTRAINT CK_NL2SQL_DEEPSEC_MIG_STATUS CHECK (STATUS IN ('PENDING', 'RUNNING', 'APPLIED', 'FAILED'))
);

-- Oracle treats an empty string as NULL. These ALTER statements also repair
-- installations created by an earlier revision of this migration.
ALTER TABLE NL2SQL_APP_ROLES MODIFY (DESCRIPTION DEFAULT '-');

ALTER TABLE NL2SQL_DEEPSEC_MIGRATIONS MODIFY (ERROR_MESSAGE DEFAULT '-');
