-- NL2SQL role permissions, data entitlements, and DeepSec ledger.
-- Users, roles, user-role assignments, and sessions are PLATFORM_* tables (platform auth, #212);
-- app_security_migrate creates them before this file. Apply before APP_AUTH_ENABLED=true startup.

CREATE TABLE NL2SQL_APP_ROLE_PERMISSIONS (
    ROLE_ID VARCHAR2(36) NOT NULL,
    PERMISSION_CODE VARCHAR2(128) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_APP_ROLE_PERMISSIONS PRIMARY KEY (ROLE_ID, PERMISSION_CODE),
    CONSTRAINT FK_NL2SQL_APP_RP_ROLE FOREIGN KEY (ROLE_ID) REFERENCES PLATFORM_ROLES (ROLE_ID)
        ON DELETE CASCADE
);

CREATE TABLE NL2SQL_APP_DATA_ENTITLEMENTS (
    ENTITLEMENT_ID VARCHAR2(36) PRIMARY KEY,
    ROLE_ID VARCHAR2(36) NOT NULL,
    RESOURCE_CODE VARCHAR2(261) NOT NULL,
    SCOPE_CODE VARCHAR2(256) NOT NULL,
    CAPABILITY VARCHAR2(64) NOT NULL,
    TARGET_OWNER VARCHAR2(128),
    TARGET_OBJECT VARCHAR2(128),
    TARGET_TYPE VARCHAR2(32) DEFAULT 'TABLE' NOT NULL,
    COLUMN_NAMES VARCHAR2(4000) DEFAULT '[]' NOT NULL,
    SCOPE_MODE VARCHAR2(32) DEFAULT 'ALL' NOT NULL,
    SCOPE_COLUMN VARCHAR2(128),
    SCOPE_FILTERS VARCHAR2(4000) DEFAULT '[]' NOT NULL,
    DATA_GRANT_NAME VARCHAR2(128),
    SQL_CHECKSUM VARCHAR2(64),
    APPLY_STATUS VARCHAR2(16) DEFAULT 'PENDING' NOT NULL,
    APPLY_ERROR_MESSAGE VARCHAR2(2000) DEFAULT '-' NOT NULL,
    APPLIED_AT TIMESTAMP WITH TIME ZONE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_NL2SQL_APP_DE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES PLATFORM_ROLES (ROLE_ID),
    CONSTRAINT CK_NL2SQL_APP_DE_TARGET_TYPE CHECK (
        TARGET_TYPE IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW')
    ),
    CONSTRAINT CK_NL2SQL_APP_DE_SCOPE_MODE CHECK (SCOPE_MODE IN ('ALL', 'COLUMN_EQUALS', 'FILTERS')),
    CONSTRAINT CK_NL2SQL_APP_DE_APPLY_STATUS CHECK (
        APPLY_STATUS IN ('PENDING', 'RUNNING', 'APPLIED', 'FAILED')
    ),
    CONSTRAINT UX_NL2SQL_APP_DE UNIQUE (ROLE_ID, RESOURCE_CODE, SCOPE_CODE, CAPABILITY)
);

CREATE TABLE NL2SQL_DEEPSEC_MIGRATIONS (
    PLAN_VERSION VARCHAR2(32) NOT NULL,
    STEP_NO NUMBER(10) NOT NULL,
    STEP_KEY VARCHAR2(128) NOT NULL,
    CHECKSUM VARCHAR2(64) NOT NULL,
    STATUS VARCHAR2(16) NOT NULL,
    ERROR_MESSAGE VARCHAR2(2000) DEFAULT '-' NOT NULL,
    EXECUTED_BY_USER_UUID VARCHAR2(36),
    EXECUTED_AT TIMESTAMP WITH TIME ZONE,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_DEEPSEC_MIGRATIONS PRIMARY KEY (PLAN_VERSION, STEP_NO),
    CONSTRAINT CK_NL2SQL_DEEPSEC_MIG_STATUS CHECK (STATUS IN ('PENDING', 'RUNNING', 'APPLIED', 'FAILED'))
);

-- Oracle treats an empty string as NULL. These ALTER statements also repair
-- installations created by an earlier revision of this migration.
ALTER TABLE NL2SQL_DEEPSEC_MIGRATIONS MODIFY (ERROR_MESSAGE DEFAULT '-');
