-- One-time, data-preserving rename of the security namespace introduced by
-- migration 004 before the product namespace was corrected to NL2SQL.
-- Fresh installations skip missing legacy objects and create NL2SQL objects
-- directly from migration 004.

RENAME RAG_APP_USERS TO NL2SQL_APP_USERS;
RENAME RAG_APP_ROLES TO NL2SQL_APP_ROLES;
RENAME RAG_APP_USER_ROLES TO NL2SQL_APP_USER_ROLES;
RENAME RAG_APP_ROLE_PERMISSIONS TO NL2SQL_APP_ROLE_PERMISSIONS;
RENAME RAG_APP_DATA_ENTITLEMENTS TO NL2SQL_APP_DATA_ENTITLEMENTS;
RENAME RAG_AUTH_SESSIONS TO NL2SQL_AUTH_SESSIONS;
RENAME RAG_AUTH_AUDIT_LOG TO NL2SQL_AUTH_AUDIT_LOG;
RENAME RAG_DEEPSEC_MIGRATIONS TO NL2SQL_DEEPSEC_MIGRATIONS;

ALTER TABLE NL2SQL_APP_USERS RENAME CONSTRAINT CK_RAG_APP_USERS_STATUS TO CK_NL2SQL_APP_USERS_STATUS;
ALTER TABLE NL2SQL_APP_USERS RENAME CONSTRAINT CK_RAG_APP_USERS_FORCE_PWD TO CK_NL2SQL_APP_USERS_FORCE_PWD;
ALTER TABLE NL2SQL_APP_ROLES RENAME CONSTRAINT CK_RAG_APP_ROLES_FLAGS TO CK_NL2SQL_APP_ROLES_FLAGS;
ALTER TABLE NL2SQL_APP_USER_ROLES RENAME CONSTRAINT PK_RAG_APP_USER_ROLES TO PK_NL2SQL_APP_USER_ROLES;
ALTER TABLE NL2SQL_APP_USER_ROLES RENAME CONSTRAINT FK_RAG_APP_UR_USER TO FK_NL2SQL_APP_UR_USER;
ALTER TABLE NL2SQL_APP_USER_ROLES RENAME CONSTRAINT FK_RAG_APP_UR_ROLE TO FK_NL2SQL_APP_UR_ROLE;
ALTER TABLE NL2SQL_APP_ROLE_PERMISSIONS RENAME CONSTRAINT PK_RAG_APP_ROLE_PERMISSIONS TO PK_NL2SQL_APP_ROLE_PERMISSIONS;
ALTER TABLE NL2SQL_APP_ROLE_PERMISSIONS RENAME CONSTRAINT FK_RAG_APP_RP_ROLE TO FK_NL2SQL_APP_RP_ROLE;
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS RENAME CONSTRAINT FK_RAG_APP_DE_ROLE TO FK_NL2SQL_APP_DE_ROLE;
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS RENAME CONSTRAINT UX_RAG_APP_DE TO UX_NL2SQL_APP_DE;
ALTER TABLE NL2SQL_AUTH_SESSIONS RENAME CONSTRAINT FK_RAG_AUTH_SESSION_USER TO FK_NL2SQL_AUTH_SESSION_USER;
ALTER TABLE NL2SQL_DEEPSEC_MIGRATIONS RENAME CONSTRAINT PK_RAG_DEEPSEC_MIGRATIONS TO PK_NL2SQL_DEEPSEC_MIGRATIONS;
ALTER TABLE NL2SQL_DEEPSEC_MIGRATIONS RENAME CONSTRAINT CK_RAG_DEEPSEC_MIG_STATUS TO CK_NL2SQL_DEEPSEC_MIG_STATUS;

ALTER INDEX UX_RAG_APP_USERS_LOGIN RENAME TO UX_NL2SQL_APP_USERS_LOGIN;
ALTER INDEX UX_RAG_APP_ROLES_CODE RENAME TO UX_NL2SQL_APP_ROLES_CODE;
ALTER INDEX PK_RAG_APP_USER_ROLES RENAME TO PK_NL2SQL_APP_USER_ROLES;
ALTER INDEX PK_RAG_APP_ROLE_PERMISSIONS RENAME TO PK_NL2SQL_APP_ROLE_PERMISSIONS;
ALTER INDEX UX_RAG_APP_DE RENAME TO UX_NL2SQL_APP_DE;
ALTER INDEX UX_RAG_AUTH_SESSION_TOKEN RENAME TO UX_NL2SQL_AUTH_SESSION_TOKEN;
ALTER INDEX IX_RAG_AUTH_SESSION_USER RENAME TO IX_NL2SQL_AUTH_SESSION_USER;
ALTER INDEX IX_RAG_AUTH_AUDIT_TIME RENAME TO IX_NL2SQL_AUTH_AUDIT_TIME;
ALTER INDEX PK_RAG_DEEPSEC_MIGRATIONS RENAME TO PK_NL2SQL_DEEPSEC_MIGRATIONS;

UPDATE NL2SQL_APP_DATA_ENTITLEMENTS
   SET RESOURCE_CODE = 'NL2SQL_DEEPSEC_PROBE'
 WHERE RESOURCE_CODE = 'DEEPSEC_PROBE';
