-- Lease/heartbeat recovery for persistent schema refresh jobs.

ALTER TABLE NL2SQL_SCHEMA_REFRESH_JOBS ADD (
    WORKER_ID VARCHAR2(256),
    HEARTBEAT_AT TIMESTAMP WITH TIME ZONE,
    LEASE_EXPIRES_AT TIMESTAMP WITH TIME ZONE,
    ATTEMPT_NO NUMBER(10)
);

UPDATE NL2SQL_SCHEMA_REFRESH_JOBS
SET ATTEMPT_NO = 0
WHERE ATTEMPT_NO IS NULL;

ALTER TABLE NL2SQL_SCHEMA_REFRESH_JOBS
    MODIFY (ATTEMPT_NO DEFAULT 0 NOT NULL);

CREATE INDEX IX_NL2SQL_SCHEMA_REFRESH_LEASE
    ON NL2SQL_SCHEMA_REFRESH_JOBS (STATUS, LEASE_EXPIRES_AT, CREATED_AT);

INSERT INTO NL2SQL_SCHEMA_MIGRATIONS (VERSION_NO, DESCRIPTION, CHECKSUM)
VALUES (6, 'incremental schema refresh job leases', 'runtime-verified');
