-- Profile / Ontology view lifecycle integrity.

DELETE FROM NL2SQL_ONTOLOGY_PROFILE_VIEW_REVISIONS view_row
WHERE NOT EXISTS (
    SELECT 1
    FROM NL2SQL_PROFILES profile_row
    WHERE profile_row.PROFILE_ID = view_row.PROFILE_ID
);

DELETE FROM NL2SQL_ONTOLOGY_PROFILE_VIEWS view_row
WHERE NOT EXISTS (
    SELECT 1
    FROM NL2SQL_PROFILES profile_row
    WHERE profile_row.PROFILE_ID = view_row.PROFILE_ID
);

ALTER TABLE NL2SQL_ONTOLOGY_PROFILE_VIEW_REVISIONS ADD CONSTRAINT
    FK_NL2SQL_ONT_VIEW_REV_PROFILE
    FOREIGN KEY (PROFILE_ID) REFERENCES NL2SQL_PROFILES (PROFILE_ID)
    ON DELETE CASCADE;

ALTER TABLE NL2SQL_ONTOLOGY_PROFILE_VIEWS ADD CONSTRAINT
    FK_NL2SQL_ONT_VIEW_PROFILE
    FOREIGN KEY (PROFILE_ID) REFERENCES NL2SQL_PROFILES (PROFILE_ID)
    ON DELETE CASCADE;

INSERT INTO NL2SQL_SCHEMA_MIGRATIONS (VERSION_NO, DESCRIPTION, CHECKSUM)
VALUES (7, 'profile ontology lifecycle integrity', 'runtime-verified');
