-- Extend existing RBAC data-entitlement rows for real DeepSec Data Grants.
-- No new application table is created by this migration.

ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS MODIFY (RESOURCE_CODE VARCHAR2(261));
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (TARGET_OWNER VARCHAR2(128));
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (TARGET_OBJECT VARCHAR2(128));
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (TARGET_TYPE VARCHAR2(32) DEFAULT 'TABLE' NOT NULL);
-- Existing deployments may have table compression enabled; adding a LOB column
-- to such tables raises ORA-39726, so keep the JSON column list in VARCHAR2.
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (COLUMN_NAMES VARCHAR2(4000) DEFAULT '[]' NOT NULL);
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (SCOPE_MODE VARCHAR2(32) DEFAULT 'ALL' NOT NULL);
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (SCOPE_COLUMN VARCHAR2(128));
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (DATA_GRANT_NAME VARCHAR2(128));
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (SQL_CHECKSUM VARCHAR2(64));
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (APPLY_STATUS VARCHAR2(16) DEFAULT 'PENDING' NOT NULL);
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (APPLY_ERROR_MESSAGE VARCHAR2(2000) DEFAULT '-' NOT NULL);
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (APPLIED_AT TIMESTAMP WITH TIME ZONE);
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL);

UPDATE NL2SQL_APP_DATA_ENTITLEMENTS
   SET TARGET_TYPE = COALESCE(TARGET_TYPE, 'TABLE'),
       COLUMN_NAMES = COALESCE(COLUMN_NAMES, '[]'),
       SCOPE_MODE = COALESCE(SCOPE_MODE, 'ALL'),
       APPLY_STATUS = COALESCE(APPLY_STATUS, 'PENDING'),
       APPLY_ERROR_MESSAGE = COALESCE(APPLY_ERROR_MESSAGE, '-'),
       UPDATED_AT = COALESCE(UPDATED_AT, SYSTIMESTAMP);

ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD CONSTRAINT CK_NL2SQL_APP_DE_TARGET_TYPE
    CHECK (TARGET_TYPE IN ('TABLE', 'VIEW', 'MATERIALIZED VIEW'));
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD CONSTRAINT CK_NL2SQL_APP_DE_SCOPE_MODE
    CHECK (SCOPE_MODE IN ('ALL', 'COLUMN_EQUALS'));
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD CONSTRAINT CK_NL2SQL_APP_DE_APPLY_STATUS
    CHECK (APPLY_STATUS IN ('PENDING', 'RUNNING', 'APPLIED', 'FAILED'));
