-- Extend DeepSec Data Grant row scope from single column equality to structured AND filters.
-- Keep the predicate payload in VARCHAR2 for compressed-table compatibility.

ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (SCOPE_FILTERS VARCHAR2(4000) DEFAULT '[]' NOT NULL);

UPDATE NL2SQL_APP_DATA_ENTITLEMENTS
   SET SCOPE_FILTERS = COALESCE(SCOPE_FILTERS, '[]');

ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS DROP CONSTRAINT CK_NL2SQL_APP_DE_SCOPE_MODE;
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD CONSTRAINT CK_NL2SQL_APP_DE_SCOPE_MODE
    CHECK (SCOPE_MODE IN ('ALL', 'COLUMN_EQUALS', 'FILTERS'));
