-- Rename application login identity from LOGIN_NAME to LOGIN_USER_ID.
-- This migration repairs existing development databases; fresh installs use 004.

ALTER TABLE NL2SQL_APP_USERS RENAME COLUMN LOGIN_NAME TO LOGIN_USER_ID;
ALTER TABLE NL2SQL_APP_USERS RENAME COLUMN LOGIN_NAME_NORMALIZED TO LOGIN_USER_ID_NORMALIZED;
ALTER INDEX UX_NL2SQL_APP_USERS_LOGIN RENAME TO UX_NL2SQL_APP_USERS_LOGIN_USER_ID;

UPDATE NL2SQL_APP_DATA_ENTITLEMENTS
   SET SCOPE_FILTERS = REPLACE(
           SCOPE_FILTERS,
           '"value_source":"APP_USER_ID"',
           '"value_source":"LOGIN_USER_ID"'
       ),
       APPLY_STATUS = CASE WHEN APPLY_STATUS = 'APPLIED' THEN 'PENDING' ELSE APPLY_STATUS END,
       SQL_CHECKSUM = NULL,
       APPLY_ERROR_MESSAGE = '-',
       APPLIED_AT = NULL
 WHERE SCOPE_FILTERS LIKE '%"value_source":"APP_USER_ID"%';
