-- Rename the internal immutable application identity from USER_ID to USER_UUID.
-- Values are preserved; only column/index/constraint names and DeepSec apply state change.

ALTER TABLE NL2SQL_APP_USERS RENAME COLUMN USER_ID TO USER_UUID;
ALTER TABLE NL2SQL_APP_USER_ROLES RENAME COLUMN USER_ID TO USER_UUID;
ALTER TABLE NL2SQL_AUTH_SESSIONS RENAME COLUMN USER_ID TO USER_UUID;
ALTER TABLE NL2SQL_DEEPSEC_MIGRATIONS RENAME COLUMN EXECUTED_BY TO EXECUTED_BY_USER_UUID;
ALTER INDEX IX_NL2SQL_AUTH_SESSION_USER RENAME TO IX_NL2SQL_AUTH_SESSION_USER_UUID;
ALTER TABLE NL2SQL_APP_USER_ROLES RENAME CONSTRAINT FK_NL2SQL_APP_UR_USER TO FK_NL2SQL_APP_UR_USER_UUID;
ALTER TABLE NL2SQL_AUTH_SESSIONS RENAME CONSTRAINT FK_NL2SQL_AUTH_SESSION_USER TO FK_NL2SQL_AUTH_SESSION_USER_UUID;

UPDATE NL2SQL_DEEPSEC_MIGRATIONS
   SET STATUS = 'PENDING',
       ERROR_MESSAGE = '-',
       EXECUTED_BY_USER_UUID = NULL,
       EXECUTED_AT = NULL,
       UPDATED_AT = SYSTIMESTAMP
 WHERE PLAN_VERSION = 'V001'
   AND STEP_KEY = 'application_context';

UPDATE NL2SQL_APP_DATA_ENTITLEMENTS
   SET APPLY_STATUS = 'PENDING',
       SQL_CHECKSUM = NULL,
       APPLY_ERROR_MESSAGE = '-',
       APPLIED_AT = NULL,
       UPDATED_AT = SYSTIMESTAMP
 WHERE APPLY_STATUS = 'APPLIED';
