-- Remove retired ontology semantic staging objects. Ontology publish uses local OWL2RL.

BEGIN EXECUTE IMMEDIATE 'DROP TABLE NL2SQL_ONTOLOGY_RDF_DATA CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE NL2SQL_ONTOLOGY_RDF_SEQ'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
