-- Role-scoped business profile access.
-- Backfill preserves existing behavior for active roles that can read profiles.

CREATE TABLE NL2SQL_APP_ROLE_PROFILES (
    ROLE_ID VARCHAR2(36) NOT NULL,
    PROFILE_ID VARCHAR2(128) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NL2SQL_APP_ROLE_PROFILES PRIMARY KEY (ROLE_ID, PROFILE_ID),
    CONSTRAINT FK_NL2SQL_APP_RPROF_ROLE FOREIGN KEY (ROLE_ID) REFERENCES NL2SQL_APP_ROLES (ROLE_ID)
);

INSERT INTO NL2SQL_APP_ROLE_PROFILES (ROLE_ID, PROFILE_ID)
SELECT r.ROLE_ID, p.PROFILE_ID
  FROM NL2SQL_APP_ROLES r
  JOIN NL2SQL_APP_ROLE_PERMISSIONS rp ON rp.ROLE_ID = r.ROLE_ID
  JOIN NL2SQL_PROFILES p ON p.ARCHIVED = 0
 WHERE r.ARCHIVED = 0
   AND r.ROLE_CODE <> 'SYSTEM_ADMIN'
   AND rp.PERMISSION_CODE = 'nl2sql.profiles.read'
   AND NOT EXISTS (
       SELECT 1
         FROM NL2SQL_APP_ROLE_PROFILES existing
        WHERE existing.ROLE_ID = r.ROLE_ID
          AND existing.PROFILE_ID = p.PROFILE_ID
   );
