CREATE TABLE NL2SQL_SYNTHETIC_RUNS (
    RUN_ID VARCHAR2(36) PRIMARY KEY,
    ACTOR_ID VARCHAR2(128) NOT NULL,
    CONTEXT_ID VARCHAR2(64) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR2(128) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    VERSION_NO NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT VARCHAR2(40) NOT NULL,
    PAYLOAD CLOB NOT NULL,
    CONSTRAINT UX_NL2SQL_SYNTHETIC_REQUEST UNIQUE (ACTOR_ID, CONTEXT_ID, IDEMPOTENCY_KEY),
    CONSTRAINT CK_NL2SQL_SYNTHETIC_JSON CHECK (PAYLOAD IS JSON)
);
CREATE TABLE NL2SQL_SYNTHETIC_LOCKS (
    CONTEXT_ID VARCHAR2(64) NOT NULL,
    TARGET_NAME VARCHAR2(300) NOT NULL,
    RUN_ID VARCHAR2(36) NOT NULL,
    PRIMARY KEY (CONTEXT_ID, TARGET_NAME),
    CONSTRAINT FK_NL2SQL_SYNTHETIC_RUN FOREIGN KEY (RUN_ID) REFERENCES NL2SQL_SYNTHETIC_RUNS(RUN_ID)
);
CREATE INDEX IX_NL2SQL_SYNTHETIC_STATE ON NL2SQL_SYNTHETIC_RUNS(CONTEXT_ID, STATUS, CREATED_AT);
