-- Structured AND/OR and bounded related EXISTS. Existing grants remain unchanged.
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD (SCOPE_EXPRESSION CLOB);
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS DROP CONSTRAINT CK_NL2SQL_APP_DE_SCOPE_MODE;
ALTER TABLE NL2SQL_APP_DATA_ENTITLEMENTS ADD CONSTRAINT CK_NL2SQL_APP_DE_SCOPE_MODE
 CHECK (SCOPE_MODE IN ('ALL', 'COLUMN_EQUALS', 'FILTERS', 'EXPRESSION'));
