-- 旧共有版は NULL 所有者として保持し、公開一意性を Profile 単位へ変更する。
-- 明示的な system schema initialize でのみ適用する。API/worker から DDL は行わない。
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE NL2SQL_ONTOLOGY_REVISIONS ADD (PROFILE_ID VARCHAR2(128))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX UX_NL2SQL_ONT_ONE_PUBLISHED';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1418 THEN RAISE; END IF;
END;
/
CREATE UNIQUE INDEX UX_NL2SQL_ONT_ONE_PUBLISHED ON NL2SQL_ONTOLOGY_REVISIONS
    (CASE WHEN STATUS = 'published' THEN NVL(PROFILE_ID, '__legacy__') END);
