-- Move shared users, roles, user-role assignments, and sessions to PLATFORM_* tables (#212).
-- RAG / NL2SQL / Agent share these tables in the same schema. Data is preserved by RENAME;
-- missing source objects are ignored so the file is idempotent. app_security_migrate stops
-- before this file when both the old and the new table exist.

ALTER TABLE NL2SQL_APP_USERS RENAME TO PLATFORM_USERS;
ALTER TABLE NL2SQL_APP_ROLES RENAME TO PLATFORM_ROLES;
ALTER TABLE NL2SQL_APP_USER_ROLES RENAME TO PLATFORM_USER_ROLES;
ALTER TABLE NL2SQL_AUTH_SESSIONS RENAME TO PLATFORM_AUTH_SESSIONS;
ALTER INDEX UX_NL2SQL_APP_USERS_LOGIN_USER_ID RENAME TO UX_PLATFORM_USERS_LOGIN_USER_ID;
ALTER INDEX UX_NL2SQL_APP_ROLES_CODE RENAME TO UX_PLATFORM_ROLES_CODE;
ALTER INDEX PK_NL2SQL_APP_USER_ROLES RENAME TO PK_PLATFORM_USER_ROLES;
ALTER INDEX UX_NL2SQL_AUTH_SESSION_TOKEN RENAME TO UX_PLATFORM_AUTH_SESSION_TOKEN;
ALTER INDEX IX_NL2SQL_AUTH_SESSION_USER_UUID RENAME TO IX_PLATFORM_AUTH_SESSION_USER_UUID;
ALTER TABLE PLATFORM_USERS RENAME CONSTRAINT CK_NL2SQL_APP_USERS_STATUS TO CK_PLATFORM_USERS_STATUS;
ALTER TABLE PLATFORM_USERS RENAME CONSTRAINT CK_NL2SQL_APP_USERS_FORCE_PWD TO CK_PLATFORM_USERS_FORCE_PWD;
ALTER TABLE PLATFORM_ROLES RENAME CONSTRAINT CK_NL2SQL_APP_ROLES_FLAGS TO CK_PLATFORM_ROLES_FLAGS;
ALTER TABLE PLATFORM_USER_ROLES RENAME CONSTRAINT PK_NL2SQL_APP_USER_ROLES TO PK_PLATFORM_USER_ROLES;
ALTER TABLE PLATFORM_USER_ROLES RENAME CONSTRAINT FK_NL2SQL_APP_UR_USER_UUID TO FK_PLATFORM_UR_USER_UUID;
ALTER TABLE PLATFORM_USER_ROLES RENAME CONSTRAINT FK_NL2SQL_APP_UR_ROLE TO FK_PLATFORM_UR_ROLE;
ALTER TABLE PLATFORM_AUTH_SESSIONS RENAME CONSTRAINT FK_NL2SQL_AUTH_SESSION_USER_UUID TO FK_PLATFORM_AUTH_SESSION_USER_UUID;
