-- Product-specific role access rows follow the shared PLATFORM_ROLES row (#212).
-- A role deleted from any product removes its NL2SQL permissions and profile access.
-- NL2SQL_APP_DATA_ENTITLEMENTS keeps a restricting FK: Data Grants must be cleaned up through
-- Deep Data Security before the role can be deleted. Drop errors (ORA-02443) are ignored.

ALTER TABLE NL2SQL_APP_ROLE_PERMISSIONS DROP CONSTRAINT FK_NL2SQL_APP_RP_ROLE;
ALTER TABLE NL2SQL_APP_ROLE_PERMISSIONS ADD CONSTRAINT FK_NL2SQL_APP_RP_ROLE
    FOREIGN KEY (ROLE_ID) REFERENCES PLATFORM_ROLES (ROLE_ID) ON DELETE CASCADE;
ALTER TABLE NL2SQL_APP_ROLE_PROFILES DROP CONSTRAINT FK_NL2SQL_APP_RPROF_ROLE;
ALTER TABLE NL2SQL_APP_ROLE_PROFILES ADD CONSTRAINT FK_NL2SQL_APP_RPROF_ROLE
    FOREIGN KEY (ROLE_ID) REFERENCES PLATFORM_ROLES (ROLE_ID) ON DELETE CASCADE;
