CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(50) NOT NULL,
    LOCATION VARCHAR2(50),
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    DEPARTMENT_ID NUMBER NOT NULL,
    EMPLOYEE_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100),
    HIRE_DATE DATE DEFAULT SYSDATE,
    SALARY NUMBER(10,2),
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT(DEPARTMENT_ID)
);

CREATE TABLE PROJECT (
    PROJECT_ID NUMBER PRIMARY KEY,
    DEPARTMENT_ID NUMBER NOT NULL,
    PROJECT_NAME VARCHAR2(100) NOT NULL,
    START_DATE DATE,
    BUDGET NUMBER(12,2),
    CONSTRAINT FK_PROJ_DEPT FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT(DEPARTMENT_ID)
);
