CREATE OR REPLACE VIEW V_EMP_DEPT AS
SELECT e.EMPLOYEE_ID, e.EMPLOYEE_NAME, e.SALARY,
       d.DEPARTMENT_NAME, d.LOCATION
  FROM EMPLOYEE e
  JOIN DEPARTMENT d
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID;

CREATE OR REPLACE VIEW V_DEPT_PROJECT AS
SELECT p.PROJECT_ID, p.PROJECT_NAME, p.BUDGET,
       d.DEPARTMENT_NAME
  FROM PROJECT p
  JOIN DEPARTMENT d
    ON p.DEPARTMENT_ID = d.DEPARTMENT_ID;
