/** Agent コンソールのルート定義。 */
export const APP_ROUTES = {
  dashboard: "/",
  agents: "/agents",
  runs: "/runs",
  approvals: "/approvals",
  audit: "/audit",
  tools: "/tools",
  memory: "/memory",
  settingsConnection: "/settings/connection",
  settingsOci: "/settings/oci",
  settingsUploadStorage: "/settings/upload-storage",
  settingsModel: "/settings/model",
  settingsDatabase: "/settings/database",
  settingsExternalRag: "/settings/external-rag",
  settingsExternalNl2Sql: "/settings/external-nl2sql",
  settingsExternalMcp: "/settings/external-mcp",
  settingsToolPolicy: "/settings/tool-policy",
  settingsCommandPolicy: "/settings/command-policy",
  settingsRuntimeSafety: "/settings/runtime-safety",
  settingsRuntimeSnapshot: "/settings/runtime-snapshot",
} as const;
