DROP VIEW SAMPLE_NL2SQL_V_SALES_DETAIL;
DROP TABLE SAMPLE_NL2SQL_SALES_ORDER CASCADE CONSTRAINTS PURGE;
DROP TABLE SAMPLE_NL2SQL_SALES_PRODUCT CASCADE CONSTRAINTS PURGE;
DROP TABLE SAMPLE_NL2SQL_SALES_CUSTOMER CASCADE CONSTRAINTS PURGE;
