CREATE TABLE SALES_CUSTOMER (
  CUSTOMER_ID NUMBER PRIMARY KEY,
  CUSTOMER_NAME VARCHAR2(100 CHAR) NOT NULL,
  REGION VARCHAR2(40 CHAR) NOT NULL
);
CREATE TABLE SALES_PRODUCT (
  PRODUCT_ID NUMBER PRIMARY KEY,
  PRODUCT_NAME VARCHAR2(100 CHAR) NOT NULL,
  CATEGORY VARCHAR2(40 CHAR) NOT NULL,
  UNIT_PRICE NUMBER(12,2) NOT NULL
);
CREATE TABLE SALES_ORDER (
  ORDER_ID NUMBER PRIMARY KEY,
  CUSTOMER_ID NUMBER NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
  ORDER_DATE DATE NOT NULL,
  QUANTITY NUMBER NOT NULL,
  SALES_AMOUNT NUMBER(12,2) NOT NULL,
  STATUS VARCHAR2(20 CHAR) NOT NULL,
  CONSTRAINT SALES_ORDER_CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES SALES_CUSTOMER(CUSTOMER_ID),
  CONSTRAINT SALES_ORDER_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES SALES_PRODUCT(PRODUCT_ID)
);
COMMENT ON TABLE SALES_CUSTOMER IS '売上サンプルの顧客';
COMMENT ON COLUMN SALES_CUSTOMER.CUSTOMER_NAME IS '顧客名';
COMMENT ON COLUMN SALES_CUSTOMER.REGION IS '地域';
COMMENT ON TABLE SALES_PRODUCT IS '売上サンプルの商品';
COMMENT ON COLUMN SALES_PRODUCT.PRODUCT_NAME IS '商品名';
COMMENT ON COLUMN SALES_PRODUCT.CATEGORY IS '商品分類';
COMMENT ON COLUMN SALES_PRODUCT.UNIT_PRICE IS '標準単価';
COMMENT ON TABLE SALES_ORDER IS '売上サンプルの受注（1受注につき1商品）';
COMMENT ON COLUMN SALES_ORDER.ORDER_DATE IS '受注日';
COMMENT ON COLUMN SALES_ORDER.QUANTITY IS '販売数量';
COMMENT ON COLUMN SALES_ORDER.SALES_AMOUNT IS '売上金額（円）';
COMMENT ON COLUMN SALES_ORDER.STATUS IS '受注状況（受注・出荷済・キャンセル）';
