CREATE OR REPLACE VIEW SAMPLE_NL2SQL_V_SALES_DETAIL AS
SELECT o.ORDER_ID, o.ORDER_DATE, c.CUSTOMER_NAME, c.REGION,
       p.PRODUCT_NAME, p.CATEGORY, o.QUANTITY, o.SALES_AMOUNT, o.STATUS
  FROM SAMPLE_NL2SQL_SALES_ORDER o
  JOIN SAMPLE_NL2SQL_SALES_CUSTOMER c ON c.CUSTOMER_ID = o.CUSTOMER_ID
  JOIN SAMPLE_NL2SQL_SALES_PRODUCT p ON p.PRODUCT_ID = o.PRODUCT_ID;
