CREATE OR REPLACE VIEW V_SALES_DETAIL AS
SELECT o.ORDER_ID, o.ORDER_DATE, c.CUSTOMER_NAME, c.REGION,
       p.PRODUCT_NAME, p.CATEGORY, o.QUANTITY, o.SALES_AMOUNT, o.STATUS
  FROM SALES_ORDER o
  JOIN SALES_CUSTOMER c ON c.CUSTOMER_ID = o.CUSTOMER_ID
  JOIN SALES_PRODUCT p ON p.PRODUCT_ID = o.PRODUCT_ID;
