/** NL2SQL コンソールのルート定義。 */
export const APP_ROUTES = {
  dashboard: "/",
  tableManagement: "/table-management",
  viewManagement: "/view-management",
  dataManagement: "/data-management",
  sampleData: "/sample-data",
  commentManagement: "/comment-management",
  annotationManagement: "/annotation-management",
  query: "/query",
  profiles: "/profiles",
  glossaryRules: "/glossary-rules",
  sqlAnalysis: "/sql-analysis",
  sqlToQuestion: "/sql-to-question",
  feedbackManagement: "/feedback-management",
  learning: "/learning",
  questionLearning: "/question-learning",
  questionClassifierModels: "/question-classifier-models",
  history: "/history",
  evaluation: "/evaluation",
  engineOperations: "/engine-operations",
  settingsOci: "/settings/oci",
  settingsUploadStorage: "/settings/upload-storage",
  settingsModel: "/settings/model",
  settingsDatabase: "/settings/database",
  nl2sqlSettingsConnection: "/settings/nl2sql-connection",
  nl2sqlSettingsModel: "/settings/nl2sql-model",
  nl2sqlSettingsDatabase: "/settings/nl2sql-database",
} as const;
