/** NL2SQL コンソールのルート定義。 */
export const APP_ROUTES = {
  dashboard: "/",
  schema: "/schema",
  dataTools: "/data-tools",
  query: "/query",
  profiles: "/profiles",
  glossaryRules: "/glossary-rules",
  sqlAnalysis: "/sql-analysis",
  learning: "/learning",
  history: "/history",
  evaluation: "/evaluation",
  engineOperations: "/engine-operations",
  settingsOci: "/settings/oci",
  settingsUploadStorage: "/settings/upload-storage",
  settingsModel: "/settings/model",
  settingsDatabase: "/settings/database",
  nl2sqlSettingsConnection: "/settings/nl2sql-connection",
  nl2sqlSettingsModel: "/settings/nl2sql-model",
  nl2sqlSettingsDatabase: "/settings/nl2sql-database",
} as const;
