"""解析済みレイアウトを Small-to-Big の親子チャンクへ変換する。

実装は責務ごとの submodule（constants / records / headings / layout / tables / evidence / search_text /
metadata / builder）にあり、ここでは公開 API とテスト・兄弟モジュールが使う名前を再 export する (#891)。
"""

from __future__ import annotations

from docrag.chunking.constants import (
    CHUNK_SCHEMA_VERSION,
    CHUNK_STRATEGY,
    CHUNKS_DIRECTORY,
    LATEST_CHUNKS_FILE,
    CHILD_CHUNK_LEVEL,
    PARENT_CHUNK_LEVEL,
    DEFAULT_CHILD_TARGET_CHARS,
    DEFAULT_TABLE_CHILD_TARGET_CHARS,
    DEFAULT_PARENT_TARGET_CHARS,
    DEFAULT_PARENT_MAX_PAGES,
    DEFAULT_PARENT_MAX_CHILDREN,
    DEFAULT_RETRIEVAL_TOP_K,
    DEFAULT_NEIGHBOR_CHILD_COUNT,
    DEFAULT_CONTEXTUAL_SEARCH_TEXT_ENABLED,
    DEFAULT_SEARCH_TEXT_CONTEXT_MAX_CHARS,
    DEFAULT_CHILD_SEARCH_TEXT_MAX_CHARS,
    CHILD_TARGET_CHARS_RANGE,
    TABLE_CHILD_TARGET_CHARS_RANGE,
    PARENT_TARGET_CHARS_RANGE,
    PARENT_MAX_PAGES_RANGE,
    PARENT_MAX_CHILDREN_RANGE,
    RETRIEVAL_TOP_K_RANGE,
    NEIGHBOR_CHILD_COUNT_RANGE,
    SEARCH_TEXT_CONTEXT_CHARS_RANGE,
    CHILD_SEARCH_TEXT_CHARS_RANGE,
    SEARCH_TEXT_SCHEMA_VERSION,
    CHUNK_METADATA_SCHEMA_VERSION,
    SOURCE_TABLE_CROP_RELATIONSHIP,
    ATOMIC_CATEGORIES,
    METADATA_ONLY_CATEGORIES,
    SECTION_CATEGORIES,
    ANNOTATION_CATEGORIES,
    CAPTION_TARGET_CATEGORIES,
    FOOTNOTE_TARGET_CATEGORIES,
    FORM_VISUAL_RAW_TYPES,
    FORM_LIKE_RAW_TYPES,
    FORM_LIKE_CATEGORIES,
    FORM_FIELD_RAW_KEYS,
    RUN_ID_PATTERN,
    CHUNK_TABLE_HEADERS,
    ChunkingConfig,
    DocumentChunk,
    ChunkingResult,
    _compact_json_text,
    _clean_search_text,
    _trim_search_text,
    _ordered_nonempty,
    SECTION_HEADER_HEADING_SOURCE,
    TITLE_HEADING_SOURCE,
    RUNNING_HEAD_HEADING_SOURCE,
    ROUTE_CAPTION_HEADING_SOURCE,
    PROMOTED_TEXT_HEADING_SOURCE,
    HEADING_SOURCES,
    _metadata_classification,
    _PAGE_NUMBER_FOOTER_PATTERN,
    _boilerplate_text_key,
    _seq_ranges,
    _unique_refs,
    _token_estimate,
    _text_sha256,
    _flatten_table_html,
    _context_preview,
    _preview,
    _page_span,
    _format_seq_ranges,
    _checked_bool,
    _checked_int,
    _int_value,
    _required_string,
    _string_list,
    _bool_value,
)
from docrag.chunking.records import (
    _record_can_supply_image_evidence,
    _record_visual_role,
    _is_attached_atomic_annotation,
    _table_structure,
    _bbox_tuple,
    _bbox_contains,
    _bbox_intersects,
    _bbox_gap,
    _bbox_horizontal_overlap,
    _relative_position,
    _list_level,
    _list_marker,
    _formula_payload,
    _form_field_payload,
    _is_form_like_record,
    _has_explicit_form_role,
    _form_record_text,
    _first_text_value,
    _raw_has_value,
    _optional_bool_value,
    _join_records_text,
    _record_text_for_chunk,
    _image_fallback_text,
    _table_visual_evidence_text,
    _table_visual_evidence_label,
    _record_text,
    _records_char_count,
    _buffer_has_body,
    _filter_image_evidence,
    _image_evidence_embedding_modality,
)
from docrag.chunking.headings import (
    _SENTENCE_BOUNDARY_PATTERN,
    _KANJI_NUMBER,
    _HEADING_LEVEL_PATTERNS,
    _CHAPTER_LEVEL,
    _LETTERED_LEVEL,
    _CIRCLED_LEVEL,
    _UNIT_MAX_LEVEL,
    _SERIES_START_PATTERN,
    _SECTION_PATH_LIMIT,
    _DOTTED_HEADING_PATTERN,
    _ROUTE_CAPTION_PATTERN,
    _RUNNING_HEADER_TOP,
    _RUNNING_FOOTER_TOP,
    _RUNNING_HEIGHT_TOLERANCE,
    _SENTENCE_HEADING_PATTERN,
    _STEP_MARKER_PATTERN,
    _MARKER_ONLY_PATTERN,
    _running_heading_keys,
    _record_height,
    _page_band,
    _promote_headings,
    _TOC_ENTRY_PATTERN,
    _TOC_MIN_ENTRIES,
    _TOC_MIN_REAPPEARING,
    _heading_key,
    _toc_entry_ids,
    _heading_level,
    _heading_form,
    _heading_source,
    _updated_section_path,
    _section_unit,
    _section_unit_cached,
    _merge_section_paths,
    _merge_section_path_sources,
    _merge_logical_page_labels,
)
from docrag.chunking.layout import (
    _is_excluded_page_boilerplate_record,
    _is_page_boilerplate_item,
    _looks_like_page_boilerplate_text,
    _visual_groups,
    _inline_icons_by_merge_target,
    _visual_group_key,
    _annotate_layout_records,
    _engine_page_key,
    _annotate_list_records,
    _annotate_list_group,
    _is_list_sequence_boundary,
    _nearest_layout_target,
    _is_annotation_target_record,
    _layout_target_score,
    _mark_layout_relationship,
    _attached_layout_annotations_by_target,
    _attached_layout_annotations,
    _attached_layout_annotations_for_targets,
    _table_contained_visual_ids,
)
from docrag.chunking.tables import (
    _table_record_with_metadata,
    _table_supplements_by_table,
    _table_row_group_records,
    _table_visual_evidence_for_row_group,
    _attach_unmatched_table_visuals,
    _table_visual_key,
    _estimated_table_row_group_bbox,
    _visual_evidence_matches_row_group,
    _contained_table_visual_evidence,
    _source_table_crop_evidence,
    _paired_picture_ocr_text,
    _table_context,
    _normalized_table_context,
)
from docrag.chunking.evidence import (
    _source_record_ref,
    _image_evidence,
    _merged_image_evidence,
    _table_image_evidence,
    _form_image_evidence,
    _is_form_visual_ref,
    _form_region_covers_fields,
    _union_ref_bboxes,
    _evidence_image_key,
    _caption_context,
    _footnote_context,
    _annotation_context,
    _list_context,
    _formula_context,
    _form_context,
    _source_categories,
    _display_regions,
)
from docrag.chunking.search_text import (
    CHILD_SEARCH_TEXT_HEADER,
    _SCREEN_EXAMPLE_PATTERN,
    _REPEATED_SEPARATOR_PATTERN,
    _without_screen_examples,
    _child_search_text,
    _append_search_component,
    _pack_search_context,
    _classification_search_text,
    _chunk_page_context_text,
    _content_signal_text,
    _table_search_text,
    _visual_search_text,
    _form_search_text,
    _formula_search_text,
    _child_search_keywords,
)
from docrag.chunking.metadata import (
    _chunk_metadata,
    _without_table_cells,
    _rounded_coordinates,
    _chunk_classification_metadata,
    _CHUNK_METADATA_REQUIRED_KEYS,
    _CHUNK_METADATA_OPTIONAL_KEYS,
    _CHUNK_LAYOUT_KEYS,
    _project_chunk_metadata,
    _validate_chunk_metadata_v4,
)
from docrag.chunking.builder import (
    build_small_to_big_chunks,
    audit_chunk_retrieval_text,
    validate_run_id,
    _build_child_chunks_for_engine,
    _split_long_text_record,
    _build_parent_chunks_for_engine,
    _child_chunk,
    _parent_chunk,
    _apply_contextual_child_search_text,
    _records_by_engine,
    _effective_engine_ids,
    _engine_labels,
    _metadata_by_page,
    _parent_should_flush,
    _source_page_count,
    _payload_classification,
    _create_chunk_run_id,
    _config_hash,
    _chunking_config_from_payload,
    _normalize_chunk_metadata,
    _chunk_from_payload,
)

def __getattr__(name: str):
    """旧 chunking API の保存・表示関数を遅延転送する。"""
    if name in ['_optional_file_sha256', '_load_latest_chunk_run_for_source_identity', '_load_viewer_payload', '_write_json', '_write_jsonl', 'chunk_payload', 'chunk_result_from_payload', 'create_chunk_run', 'load_chunk_run_by_id', 'load_latest_chunk_run', 'load_latest_chunk_run_for_run_source', 'load_latest_chunk_run_for_source', 'load_latest_or_source_chunk_run']:
        from importlib import import_module
        return getattr(import_module("docrag.chunking.storage"), name)
    if name in ['chunk_table_rows', 'summarize_chunk_run']:
        from importlib import import_module
        return getattr(import_module("docrag.chunking.presentation"), name)
    raise AttributeError(name)
