/** RAG コンソールの画面ルート定義。 */
export const APP_ROUTES = {
  login: "/login",
  dashboard: "/dashboard",
  upload: "/upload",
  fileList: "/file-list",
  knowledgeBases: "/knowledge-bases",
  documents: "/documents",
  search: "/search",
  evaluation: "/evaluation",
  settingsOci: "/settings/oci",
  settingsUploadStorage: "/settings/upload-storage",
  settingsPreprocess: "/settings/preprocess",
  settingsParserAdapters: "/settings/parser-adapters",
  settingsChunking: "/settings/chunking",
  settingsRetrieval: "/settings/retrieval",
  settingsGrounding: "/settings/grounding",
  settingsGeneration: "/settings/generation",
  settingsGuardrail: "/settings/guardrail",
  settingsVectorIndex: "/settings/vector-index",
  settingsEvaluation: "/settings/evaluation",
  settingsGraph: "/settings/graph",
  settingsAgentic: "/settings/agentic",
  settingsModel: "/settings/model",
  settingsDatabase: "/settings/database",
  settingsPrompts: "/settings/prompts",
} as const;
