"""共通 API インフラ（エラー envelope / 検証エラーの整形 / pagination / health）。"""

from .errors import (
    api_error_response,
    http_exception_messages,
    install_exception_handlers,
)
from .health import create_health_router
from .pagination import (
    ACCESS_TARGET_PAGE_LIMIT_MAX,
    CURSOR_MAX_LENGTH,
    DEFAULT_PAGE_LIMIT,
    DEFAULT_PAGE_LIMIT_MAX,
    CursorParams,
    InvalidCursorError,
    OffsetParams,
    cursor_page,
    cursor_params,
    decode_cursor,
    decode_offset_cursor,
    empty_page,
    encode_cursor,
    encode_offset_cursor,
    has_next_page,
    next_offset_cursor,
    offset_fetch_binds,
    offset_fetch_clause,
    offset_params,
    paginate,
    paginate_slice,
)
from .validation import (
    validation_error_content,
    validation_error_messages,
    validation_error_response,
    validation_field_errors,
    validation_tool_errors,
)

__all__ = [
    "api_error_response",
    "http_exception_messages",
    "install_exception_handlers",
    "create_health_router",
    "ACCESS_TARGET_PAGE_LIMIT_MAX",
    "CURSOR_MAX_LENGTH",
    "DEFAULT_PAGE_LIMIT",
    "DEFAULT_PAGE_LIMIT_MAX",
    "CursorParams",
    "InvalidCursorError",
    "OffsetParams",
    "cursor_page",
    "cursor_params",
    "decode_cursor",
    "decode_offset_cursor",
    "empty_page",
    "encode_cursor",
    "encode_offset_cursor",
    "has_next_page",
    "next_offset_cursor",
    "offset_fetch_binds",
    "offset_fetch_clause",
    "offset_params",
    "paginate",
    "paginate_slice",
    "validation_error_content",
    "validation_error_messages",
    "validation_error_response",
    "validation_field_errors",
    "validation_tool_errors",
]
