"""モデルのテストに送る入力（3製品で共通。#745）。

システム設定 > モデル設定の「テスト」は、製品ごとの client（RAG / NL2SQL の
`OciEnterpriseAiClient`、Agent の自前の payload）で呼ぶが、送る入力はここの 1 セットを使う。
"""

from __future__ import annotations

import base64
from collections.abc import Sequence
from typing import Final

MODEL_TEST_TEXT_PROMPT: Final = "モデル接続テストです。短く応答してください。"
MODEL_TEST_VISION_PROMPT: Final = "白い背景にある大きな図形の色を日本語で1語だけ返してください。"
MODEL_TEST_EMBEDDING_INPUT: Final = "モデル接続テスト"
MODEL_TEST_RERANK_QUERY: Final = "モデル接続テスト"
MODEL_TEST_RERANK_DOCUMENTS: Final[Sequence[str]] = (
    "これはモデル接続テストに関する候補文書です。",
    "別の業務文書に関する候補文書です。",
)

# 512×512 の JPEG（白地に赤い正方形）。1×1 の PNG のような小さい画像は、
# gateway が不正な画像として 400 で拒否する（xAI の `invalid_image`。#745）。
MODEL_TEST_IMAGE_MIME_TYPE: Final = "image/jpeg"
MODEL_TEST_IMAGE_BYTES: Final = base64.b64decode(
    "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsO"
    "CwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ"
    "EBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAIAAgADASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAA"
    "AAYJA//EACQQAQABAAsBAQEBAAAAAAAAAAAHAwQFBhc3V3aWtNMBAhEh/8QAGQEBAAMBAQAAAAAAAAAAAAAAAAMH"
    "CAQB/8QAKBEBAAECAA8BAQAAAAAAAAAAAAECAwQFExUzNFJTcXKRkrGy0TER/9oADAMBAAIRAxEAPwDVMAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGJgCrG8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGvkHZKR"
    "/tayupRLdEQdkpH+1rK6lEt1nWNFTwjww3jXX7/PV7SAJXAAAAAAAAAAAAAAAAAAAAAxMAVY3mAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAA18g7JSP9rWV1KJboiDslI/2tZXUolus6xoqeEeGG8a6/f56vaQBK4AAAAAAAAAAA"
    "AAAAAAAAAGJgCrG8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGvkHZKR/tayupRLdEQdkpH+1rK6lEt1nWN"
    "FTwjww3jXX7/AD1e0gCVwAAAAAAAAAAAAAAAAAAAAMTAFWN5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANf"
    "IOyUj/a1ldSiW6Ig7JSP9rWV1KJbrOsaKnhHhhvGuv3+er2kASuAAAAAAAAAAAAAAAAAAAABiYAqxvMAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAABr5B2Skf7WsrqUS3REHZKR/tayupRLdZ1jRU8I8MN411+/z1e0gCVwAAAAAA"
    "AAAAAAAAAAAAAAMTAFWN5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANfIOyUj/a1ldSiW6Ig7JSP9rWV1KJ"
    "brOsaKnhHhhvGuv3+er2kASuAAAAAAAAAAAAAAAAAAAABiYAqxvMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "ABr5B2Skf7WsrqUS3REHZKR/tayupRLdZ1jRU8I8MN411+/z1e0gCVwAAAAAAAAAAAAAAAAAAAAMTAFWN5gAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANfIOyUj/AGtZXUoluiIOyUj/AGtZXUolus6xoqeEeGG8a6/f56vaQBK4"
    "AAAAAAAAAAAAAAAAAAAAGJgCrG8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGvkHZKR/tayupRLdEQdkpH+"
    "1rK6lEt1nWNFTwjww3jXX7/PV7SAJXAAAAAAAAAAAAAAAAAAAAAxMAVY3mAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAA18g7JSP9rWV1KJboiDslI/2tZXUolus6xoqeEeGG8a6/f56vaQBK4AAAAAAAAAAAAAAAAAAAAGJgCrG8"
    "wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGvkHZKR/tayupRLdEQdkpH+1rK6lEt1nWNFTwjww3jXX7/AD1e"
    "0gCVwAAAAAAAAAAAAAAAAAAAAMTAFWN5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANfIOyUj/a1ldSiW6Ig"
    "7JSP9rWV1KJbrOsaKnhHhhvGuv3+er2kASuAAAAAAAAAAAAAAAAAAAABiYAqxvMAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAABr5B2Skf7WsrqUS3REHZKR/tayupRLdZ1jRU8I8MN411+/z1e0gCVwAAAAAAAAAAAAAAAAAAAAMT"
    "AFWN5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANfIOyUj/a1ldSiW6Ig7JSP9rWV1KJbrOsaKnhHhhvGuv3"
    "+er2kASuAAAAAAAAAAAAAAAAAAAABiYAqxvMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABr5B2Skf7WsrqUS"
    "3REHZKR/tayupRLdZ1jRU8I8MN411+/z1e0gCVwAAAAAAAAAAAAAAAAAAAAMTAFWN5gAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAANfIOyUj/AGtZXUoluiIOyUj/AGtZXUolus6xoqeEeGG8a6/f56vaQBK4AAAAAAAAAAAAAAAA"
    "AAAAGJgCrG8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGvkHZKR/tayupRLdEQdkpH+1rK6lEt1nWNFTwjw"
    "w3jXX7/PV7SAJXAAAAAAAAAAAAAAAAAAAAAxMAVY3mAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA18g7JSP9"
    "rWV1KJboiDslI/2tZXUolus6xoqeEeGG8a6/f56vaQBK4AAAAAAAAAAAAAAAAAAAAGJgCrG8wAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAGvkHZKR/tayupRLdEQdkpH+1rK6lEt1nWNFTwjww3jXX7/AD1e0gCVwAAAAAAAAAAA"
    "AAAAAAAAAMTAFWN5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANfIOyUj/a1ldSiW6Ig7JSP9rWV1KJbrOsa"
    "KnhHhhvGuv3+er2kASuAAAAAAAAAAAAAAAAAAAABEYHQpo/cnj9U8zA6FNH7k8fqnmtxFkLWzHSHfnXD9/X3VfUR"
    "gdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkGdcP39fdV9RGB0KaP3J4/VPMwOhTR+5PH6p5rcMha2Y6QZ1w/f191X1"
    "EYHQpo/cnj9U8zA6FNH7k8fqnmtwyFrZjpBnXD9/X3VfURgdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkGdcP39fdV"
    "9RGB0KaP3J4/VPMwOhTR+5PH6p5rcMha2Y6QZ1w/f191X1EYHQpo/cnj9U8zA6FNH7k8fqnmtwyFrZjpBnXD9/X3"
    "VfURgdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkGdcP39fdV9RGB0KaP3J4/VPMwOhTR+5PH6p5rcMha2Y6QZ1w/f1"
    "91X1EYHQpo/cnj9U8zA6FNH7k8fqnmtwyFrZjpBnXD9/X3VfURgdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkGdcP3"
    "9fdV9RGB0KaP3J4/VPMwOhTR+5PH6p5rcMha2Y6QZ1w/f191X1EYHQpo/cnj9U8zA6FNH7k8fqnmtwyFrZjpBnXD"
    "9/X3VfURgdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkGdcP39fdV9RGB0KaP3J4/VPMwOhTR+5PH6p5rcMha2Y6QZ1"
    "w/f191X1EYHQpo/cnj9U8zA6FNH7k8fqnmtwyFrZjpBnXD9/X3VfURgdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkG"
    "dcP39fdV9RGB0KaP3J4/VPMwOhTR+5PH6p5rcMha2Y6QZ1w/f191X1EYHQpo/cnj9U8zA6FNH7k8fqnmtwyFrZjp"
    "BnXD9/X3VfURgdCmj9yeP1TzMDoU0fuTx+qea3DIWtmOkGdcP39fdV9cKjUalZdSq9m2bU6CqVOqUX4oKvV6Cj+U"
    "dHQ0f5+fPz+fx+Pz+f58/P5+fPnz58+fP8+fPjuCX8cMzNU/2f0AHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//2Q=="
)


def model_test_text_context(product_name: str) -> str:
    """テキストのテストに添えるコンテキスト（例: `Production Ready RAG`）。"""
    return f"これは {product_name} のモデル接続テスト用コンテキストです。"


def model_test_image_data_url() -> str:
    """テスト画像の data URL（OpenAI 互換の `input_image` の `image_url` に渡す）。"""
    encoded = base64.b64encode(MODEL_TEST_IMAGE_BYTES).decode("ascii")
    return f"data:{MODEL_TEST_IMAGE_MIME_TYPE};base64,{encoded}"
