DROP VIEW SAMPLE_NL2SQL_V_INQUIRY_DETAIL;
DROP TABLE SAMPLE_NL2SQL_INQUIRY_TICKET CASCADE CONSTRAINTS PURGE;
DROP TABLE SAMPLE_NL2SQL_INQUIRY_CATEGORY CASCADE CONSTRAINTS PURGE;
DROP TABLE SAMPLE_NL2SQL_INQUIRY_CUSTOMER CASCADE CONSTRAINTS PURGE;
