CREATE TABLE INQUIRY_CUSTOMER (
  CUSTOMER_ID NUMBER PRIMARY KEY,
  CUSTOMER_NAME VARCHAR2(100 CHAR) NOT NULL,
  REGION VARCHAR2(40 CHAR) NOT NULL
);
CREATE TABLE INQUIRY_CATEGORY (
  CATEGORY_ID NUMBER PRIMARY KEY,
  CATEGORY_NAME VARCHAR2(100 CHAR) NOT NULL
);
CREATE TABLE INQUIRY_TICKET (
  TICKET_ID NUMBER PRIMARY KEY,
  CUSTOMER_ID NUMBER NOT NULL,
  CATEGORY_ID NUMBER NOT NULL,
  SUBJECT VARCHAR2(200 CHAR) NOT NULL,
  OPENED_DATE DATE NOT NULL,
  RESOLVED_DATE DATE,
  STATUS VARCHAR2(20 CHAR) NOT NULL,
  PRIORITY VARCHAR2(20 CHAR) NOT NULL,
  CONSTRAINT INQUIRY_TICKET_CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES INQUIRY_CUSTOMER(CUSTOMER_ID),
  CONSTRAINT INQUIRY_TICKET_CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES INQUIRY_CATEGORY(CATEGORY_ID)
);
COMMENT ON TABLE INQUIRY_CUSTOMER IS '問い合わせサンプルの顧客';
COMMENT ON COLUMN INQUIRY_CUSTOMER.CUSTOMER_NAME IS '顧客名';
COMMENT ON COLUMN INQUIRY_CUSTOMER.REGION IS '地域';
COMMENT ON TABLE INQUIRY_CATEGORY IS '問い合わせの分類';
COMMENT ON COLUMN INQUIRY_CATEGORY.CATEGORY_NAME IS '問い合わせ分類名';
COMMENT ON TABLE INQUIRY_TICKET IS '問い合わせの対応履歴';
COMMENT ON COLUMN INQUIRY_TICKET.SUBJECT IS '問い合わせ件名';
COMMENT ON COLUMN INQUIRY_TICKET.OPENED_DATE IS '受付日';
COMMENT ON COLUMN INQUIRY_TICKET.RESOLVED_DATE IS '解決日（未解決は空）';
COMMENT ON COLUMN INQUIRY_TICKET.STATUS IS '対応状況（受付・対応中・解決済）';
COMMENT ON COLUMN INQUIRY_TICKET.PRIORITY IS '優先度（高・中・低）';
