CREATE OR REPLACE VIEW SAMPLE_NL2SQL_V_INQUIRY_DETAIL AS
SELECT t.TICKET_ID, c.CUSTOMER_NAME, c.REGION, k.CATEGORY_NAME,
       t.SUBJECT, t.OPENED_DATE, t.RESOLVED_DATE, t.STATUS, t.PRIORITY
  FROM SAMPLE_NL2SQL_INQUIRY_TICKET t
  JOIN SAMPLE_NL2SQL_INQUIRY_CUSTOMER c ON c.CUSTOMER_ID = t.CUSTOMER_ID
  JOIN SAMPLE_NL2SQL_INQUIRY_CATEGORY k ON k.CATEGORY_ID = t.CATEGORY_ID;
