CREATE OR REPLACE VIEW V_INQUIRY_DETAIL AS
SELECT t.TICKET_ID, c.CUSTOMER_NAME, c.REGION, k.CATEGORY_NAME,
       t.SUBJECT, t.OPENED_DATE, t.RESOLVED_DATE, t.STATUS, t.PRIORITY
  FROM INQUIRY_TICKET t
  JOIN INQUIRY_CUSTOMER c ON c.CUSTOMER_ID = t.CUSTOMER_ID
  JOIN INQUIRY_CATEGORY k ON k.CATEGORY_ID = t.CATEGORY_ID;
